# Generated by Django 5.1.6 on 2025-02-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "accommodation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Hotel", "Hotel"),
                            ("Hostel", "Hostel"),
                            ("Homestay", "Homestay"),
                            ("Resort", "Resort"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyService",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Police", "Police"),
                            ("Hospital", "Hospital"),
                            ("Embassy", "Embassy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="FoodSafetyRating",
            fields=[
                ("place_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("hygiene_score", models.DecimalField(decimal_places=2, max_digits=3)),
                ("fssai_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                ("itinerary_id", models.AutoField(primary_key=True, serialize=False)),
                ("destination", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SafetyAlert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("Crime", "Crime"),
                            ("Protest", "Protest"),
                            ("Disaster", "Disaster"),
                            ("Accident", "Accident"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransportOption",
            fields=[
                ("transport_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Train", "Train"),
                            ("Flight", "Flight"),
                            ("Bus", "Bus"),
                            ("Auto", "Auto"),
                            ("Taxi", "Taxi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.IntegerField()),
                ("departure_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Traveler", "Traveler"),
                            ("Admin", "Admin"),
                            ("Community", "Community"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Transport", "Transport"),
                            ("Food", "Food"),
                            ("Stay", "Stay"),
                            ("Misc", "Misc"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traveller.itinerary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostAndFound",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                ("item_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Lost", "Lost"),
                            ("Found", "Found"),
                            ("Recovered", "Recovered"),
                        ],
                        max_length=10,
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "LostAndFound",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="traveller.user",
                    ),
                ),
                ("preferred_language", models.CharField(max_length=50)),
                ("budget_range", models.CharField(max_length=50)),
                (
                    "travel_type",
                    models.CharField(
                        choices=[
                            ("Solo", "Solo"),
                            ("Group", "Group"),
                            ("Family", "Family"),
                            ("Business", "Business"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPermit",
            fields=[
                ("permit_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("applied_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("Maps", "Maps"),
                            ("EmergencyContacts", "EmergencyContacts"),
                            ("Permits", "Permits"),
                            ("Translator", "Translator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itinerary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
            ),
        ),
        migrations.CreateModel(
            name="GroupExpense",
            fields=[
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("split_between", models.CharField(max_length=255)),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "recommendation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("Hotel", "Hotel"),
                            ("Transport", "Transport"),
                            ("Food", "Food"),
                            ("Safety", "Safety"),
                        ],
                        max_length=10,
                    ),
                ),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("Scam", "Scam"),
                            ("Crime", "Crime"),
                            ("Accident", "Accident"),
                            ("Unsafe Area", "Unsafe Area"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("report_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveller.user"
                    ),
                ),
            ],
        ),
    ]
