# Generated by Django 5.1.6 on 2025-02-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traveller", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lostandfound",
            name="user_id",
        ),
        migrations.AddField(
            model_name="lostandfound",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="traveller.user",
            ),
        ),
    ]
