# Generated by Django 5.1.6 on 2025-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traveller", "0002_remove_lostandfound_user_id_lostandfound_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostandfound",
            name="date_found",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
