# Generated by Django 5.1.6 on 2025-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traveller", "0003_lostandfound_date_found"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loved_ones",
            field=models.JSONField(default=list),
        ),
    ]
